# Get Metadata of Service 
### 
###
GET http://localhost:4004/odata/v4/regulation-compliance-transaction/RegulationComplianceTransaction 

# Create Message on Event Mesh
###
POST http://localhost:4004/odata/v4/regulation-compliance-transaction/sendMessage
Content-Type: application/json

{
    "data": {
    "RenewableMaterial":"300003",
    "RenewableEventType":"GM",
    "RenewableFuelCategory":"GS",
    "RenewableTransactionType":"PUR",
    "RegulationGroupName":"R001",
    "RegulationMateGroup":"M001",
    "MaterialDescription":"UNLEADED PREMIUM 91",
    "_RenewableContract":{
      "RenewableMaterial":"",
      "RenewableEventType":"",
      "RenwableContract":"",
      "RenwableCotractItem":"0",
      "DocumentType":"",
      "MovementType":"",
      "Quantity": "0.000",
      "UnitOfMeasure":""
    },
    "_RenewableDeal":{
      "RenewableMaterial":"",
      "RenewableEventType":"",
      "RenwableDealDocument":"",
      "RenwableDealItem":"0",
      "DocumentType":"",
      "MovementType":"",
      "AttachedIndicator":"",
      "Dcode":"",
      "VintageYear":"0",
      "Multiplier":"",
      "RINObligation":"",
      "RINsGenerator":"",
      "RINspriced":"",
      "QAPcertified":"",
      "Quantity": "0.000",
      "UnitOfMeasure":"",
      "RenewablePassRetainIndicator":false,
      "RenewableDealNumber":"",
      "RenewableDcodeription":"",
      "RenewableVintageYearription":"0",
      "RenewableRinMultiplierription":"0",
      "RenewableQapCertifiedription":""
    },
    "_RenewableDelivery":{
      "RenewableMaterial":"",
      "RenewableEventType":"",
      "RenwableDelivery":"",
      "RenwableDeliveryItem":"0",
      "DocumentType":"",
      "MovementType":"",
      "Quantity": "0.000",
      "UnitOfMeasure":""
    },
    "_RenewableMaterialDocument":{
      "RenewableMaterial":"300003",
      "RenewableEventType":"WF",
      "RenwableMaterialDocument":"10001010",
      "RenwableMaterialDocumentItem":"10",
      "DocumentType":"",
      "MovementType":"101",
      "Plant":"",
      "StorageLocation":"",
      "CompanyCode":"",
      "DocumentDate":"2024-07-03",
      "Quantity": "10000",
      "UnitOfMeasure":"UG6",
      "RenewableMaterialDocDocDte":null,
      "RenewableMaterialDocPostgDte":null,
      "RenewableBillOfLading":"",
      "RenewableReasonReasonCode":"0",
      "RenewableReversalPostingDate":null
    },
    "_RenewableNominationData":{
      "RenewableMaterial":"",
      "RenewableEventType":"",
      "RenwableNomination":"",
      "NominationKey":"",
      "RenwableNominationItem":"0",
      "DocumentType":"",
      "MovementType":"",
      "Quantity": "0.000",
      "UnitOfMeasure":""
    },
    "_RenewableProductionOrder":{
      "RenewableMaterial":"",
      "RenewableEventType":"",
      "RenwableProductionOrder":"",
      "RenwableProductionOrderItem":"0",
      "DocumentType":"",
      "MovementType":"",
      "Quantity": "0.000",
      "UnitOfMeasure":"",
      "RenewableBusinessPartnerNumber":"",
      "RenewableBusinessPartnerDesc":"",
      "RenewableIncoTerms1":"",
      "RenewableIncoTerms2":"",
      "RenewableContract":"",
      "RenewableContractItem":"0"
    },
    "_RenewablePurchaseOrder":{
      "RenewableMaterial":"300003",
      "RenewableEventType":"WF",
      "RenwablePurchaseOrder":"",
      "RenwablePurchaseOrderItem":"0",
      "DocumentType":"",
      "MovementType":"521",
      "Quantity": "10000",
      "UnitOfMeasure":"UG6"
    },
    "_RenewableSalesOrder":{
      "RenewableMaterial":"",
      "RenewableEventType":"",
      "RenwableSalesOrder":"",
      "RenwableSalesOrderItem":"0",
      "DocumentType":"",
      "MovementType":"",
      "Quantity": "0.000",
      "UnitOfMeasure":""
    },
    "_RenewableTicketData":{
      "RenewableMaterial":"",
      "RenewableEventType":"",
      "RenwableTicket":"",
      "RenwableTicketItem":"0",
      "Ticketkey":"",
      "TicketVersion":"0",
      "TicketPurpose":"",
      "Tickettype":"",
      "ExternalTicketNumber":"",
      "ExternalPositionNumber":"",
      "DocumentType":"",
      "MovementType":"",
      "Quantity": "0.000",
      "UnitOfMeasure":""
    }
 }
}


# Call Action processEvent 
###
POST http://localhost:4004/odata/v4/regulation-compliance-transaction/processEvent
Content-Type: application/json

{
    "eventData": [
        {
            "regulationMaterial": "1059392",
            "regulationEventType": "RFS2",
            "regulationFuelCategory": "GS",
            "fuelSubCategory": "BD",
            "regulationGroupName": "R003",
            "regulationMaterialGroupName": "M001",
            "documentDate": "2024-06-18",
            "incotermsPart1": "FOB",
            "incotermsPart2": "BPUSPDX",
            "movementType": "101",
            "originRegion": "",
            "destinationRegion": "",
            "modeofTransport": "11",
            "fuelQuantity": "420.000",
            "fuelUnitofMeasurement": "UG6",
            "dcode": "",
            "vintageYear": "2024",
            "rinMultiplier": 1,
            "sourceOrgCode": "",
            "qapCertified": "",
            "businessPartnerNumber": "",
            "businessPartnerDesc": "",
            "billofLading": "99123",
            "passRetainIndicator": "",
            "reversalPostingDate": "2024-06-18",
            "referenceContractGeneralDocumentNumber": "",
            "referenceContractDocumentItemNumber": "",
            "sourceOrgMaterialNumber": "1059392",
            "sourceOrgMaterialNumberDesc": "Gasoline",
            "postingDate": "2024-06-18",
            "obligationMaterialDocumentNumber": "5000001",
            "obligationMaterialDocumentItemNumber": "0010",
            "obligationReverseMaterialDocumentNumber": "",
            "obligationReverseMaterialDocumentItemNumber": "",
            "rfOrder": "",
            "rfOrderItem": "",
            "sourceOrgPlant": "0563",
            "sourceOrgStorageLocation": "1000"
        }
    ]
}


# Call Action trans 
###
POST http://localhost:4004/odata/v4/regulation-compliance-transaction/RegulationComplianceTransaction
Content-Type: application/json

{
    "regulationType": "RFS2",
    "regulationCategory": "RFS2",
    "objectCategory": "D",
    "objectType": "RVO",
    "sourceScenario": "GM",
    "subObjectScenario": "RFS2_RVO",
    "transactionCategory": "PUR",
    "transactionType": "PUR1"
}

# Call on Create trans 
###
POST http://localhost:4004/odata/v4/regulation-compliance-transaction/ManualAdjRegulationComplianceTransaction
Content-Type: application/json

{
    "objectId": 923,
    "regulationType": "RFS2",
    "regulationCategory": "RFS2",
    "objectCategory": "D",
    "objectType": "RVO",
    "processingStatus":"01",
    "sourceScenario": "MDJ",
    "subObjectScenario": "RFS2_MDJ_RVO",
    "transactionCategory": "PUR",
    "transactionType": "PUR1",
    "impact": "I",
    "documentDate":"2024-06-01",
    "renewablesDocumentMonth": "06",
    "renewablesDocumentComplianceYear": "2024",
    "businessPartnerNumber":"1234",
    "reasonCode":"30",
    "sourceOrgPlant":"1000",
    "regulationQuantity": 200,
    "regulationUnitOfMeasurement": "RIN",
    "regulationLogisticsMaterialNumber":"CELLULOSIC_2024"

}
# Get Metadata of Service 
###
GET http://localhost:4004/odata/v4/regulation-compliance-transaction/MaintainRegulationType 

# Get Metadata of Service 
###
GET http://localhost:4004/odata/v4/regulation-compliance-transaction/ManualAdjRegulationComplianceTransaction

###
POST http://localhost:4004/odata/v4/regulation-compliance-transaction/actionTrigger
Content-Type: application/json

{ "actionName":"PIP", "objectKey":"4615134b-d75f-472e-bdf8-4ee74f7f59ca" }
###
POST http://localhost:4004/odata/v4/regulation-compliance-transaction/Actions
Content-Type: application/json

{
    "actionName": "PIP",
    "regSubScn": "RFS2_RVO"
}


###
GET http://localhost:4004/odata/v4/regulation-compliance-transaction/Actions